import 'dart:collection';

import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:nanoid/non_secure.dart';

import 'attributes.dart';
import 'delta/text_delta.dart';
import 'path.dart';

abstract class NodeExternalValues {
  const NodeExternalValues();
}

/// [Node] represents a node in the document tree.
///
/// It contains three parts:
///   - [type]: The type of the node to determine which block component to
///     render it.
///   - [data]: The data of the node to determine how to render it.
///   - [children]: The children of the node.
///
///
/// Json format:
/// ```
/// {
///   'type': String,
///   'data': Map<String, Object>
///   'children': List<Node>,
/// }
/// ```
///
final class Node extends ChangeNotifier with LinkedListEntry<Node> {
  Node({
    required this.type,
    String? id,
    this.parent,
    Attributes attributes = const {},
    Iterable<Node> children = const [],
  })  : _children = LinkedList<Node>()
          ..addAll(
            children.map(
              (e) => e..unlink(),
            ),
          ), // unlink the given children to avoid the error of "node has
              // already a parent"
        _attributes = attributes,
        id = id ?? nanoid(6) {
    for (final child in children) {
      child.parent = this;
    }
  }

  /// Parses a [Map] into a [Node]
  ///
  factory Node.fromJson(Map<String, Object> json) {
    final node = Node(
      type: json['type'] as String,
      attributes: Attributes.from(json['data'] as Map? ?? {}),
      children: (json['children'] as List? ?? [])
          .map((e) => Map<String, Object>.from(e))
          .map((e) => Node.fromJson(e)),
    );

    for (final child in node.children) {
      child.parent = node;
    }

    return node;
  }

  /// The type of the node.
  final String type;

  /// The id of the node.
  ///
  /// If not provided, it will be generated by [nanoid].
  /// In most cases, you don't need to modify it after the node is created.
  String id;

  @Deprecated('Use type instead')
  String get subtype => type;

  /// The parent of the node.
  Node? parent;

  /// The children of the node.
  final LinkedList<Node> _children;
  List<Node> get children {
    _cacheChildren ??= _children.toList(growable: false);
    return _cacheChildren!;
  }

  List<Node>? _cacheChildren;

  /// Bumped on every children mutation; used to validate the per-child
  /// index cache that keeps [path] cheap (see [_indexInParent]).
  int _childrenVersion = 0;

  // index-in-parent cache (owned by the parent's version).
  Node? _indexCacheOwner;
  int _indexCacheVersion = -1;
  int _cachedIndex = -1;

  // parsed-delta cache, keyed by the identity of the raw attribute list.
  Object? _cachedDeltaRaw;
  Delta? _cachedDelta;

  void _invalidateChildrenCache() {
    _cacheChildren = null;
    _childrenVersion++;
  }

  /// Test-only instrumentation: number of full sibling re-index sweeps
  /// performed by [_reindexChildren]. Lets tests prove that repeated
  /// [path] reads are cache hits (the counter must not move).
  @visibleForTesting
  static int debugReindexCount = 0;

  /// Test-only instrumentation: number of times a [Delta] was parsed from
  /// its raw attribute value — i.e. the cache misses of [delta].
  @visibleForTesting
  static int debugDeltaParseCount = 0;

  /// The attributes of the node.
  Attributes _attributes;
  Attributes get attributes => {..._attributes};

  /// The path of the node.
  Path get path => _computePath();

  NodeExternalValues? externalValues;

  /// this value is used to store temporary data,
  ///   and will be cleared after the node is rendered
  Map? extraInfos;

  // Render Part
  final key = GlobalKey();
  final layerLink = LayerLink();

  void notify() {
    notifyListeners();
  }

  /// Update the attributes of the node.
  ///
  void updateAttributes(Attributes attributes) {
    _attributes = composeAttributes(this.attributes, attributes) ?? {};

    notifyListeners();
  }

  /// Grabs the [Node] from this [Node]s children
  /// at a given index, if the index exists.
  ///
  Node? childAtIndexOrNull(int index) {
    if (children.length <= index || index < 0) {
      return null;
    }

    return children.elementAt(index);
  }

  Node? childAtPath(Path path) {
    // iterative on purpose: the recursive version allocated one
    // `path.sublist(1)` per level on one of the hottest lookup paths of
    // the editor (every selection check resolves nodes by path).
    Node? node = this;
    for (final index in path) {
      node = node?.childAtIndexOrNull(index);
      if (node == null) {
        return null;
      }
    }
    return node;
  }

  /// Inserts a [Node] at a given [index]
  ///
  /// If no [index] is supplied, inserts at the
  /// end of the [Node].
  ///
  void insert(Node entry, {int? index}) {
    final length = _children.length;
    index ??= length;

    entry._resetRelationshipIfNeeded();
    entry.parent = this;

    _invalidateChildrenCache();

    if (_children.isEmpty) {
      _children.add(entry);
      notifyListeners();
      return;
    }

    // If index is out of range, insert at the end.
    // If index is negative, insert at the beginning.
    // If index is positive, insert at the index.
    if (index >= length) {
      _children.last.insertAfter(entry);
    } else if (index <= 0) {
      _children.first.insertBefore(entry);
    } else {
      childAtIndexOrNull(index)?.insertBefore(entry);
    }
  }

  @override
  void insertAfter(Node entry) {
    entry._resetRelationshipIfNeeded();
    entry.parent = parent;
    super.insertAfter(entry);

    parent?._invalidateChildrenCache();

    // Notifies the new node.
    parent?.notifyListeners();
  }

  @override
  void insertBefore(Node entry) {
    entry._resetRelationshipIfNeeded();
    entry.parent = parent;
    super.insertBefore(entry);

    parent?._invalidateChildrenCache();

    // Notifies the new node.
    parent?.notifyListeners();
  }

  @override
  bool unlink() {
    // Add a null check to avoid unlink failure
    if (parent == null || list == null) {
      return false;
    }
    super.unlink();

    parent?._invalidateChildrenCache();

    parent?.notifyListeners();
    parent = null;
    return true;
  }

  // reset the relationship of the node before inserting it to another node
  //  to ensure it is not in the tree
  // otherwise, it will throw a state error
  //  'Bad state: LinkedNode is already in a LinkedList'
  void _resetRelationshipIfNeeded() {
    if (parent != null || list != null) {
      unlink();
    }
  }

  @override
  String toString() {
    return 'Node(id: $id, type: $type, attributes: $attributes, '
        'children: $children)';
  }

  /// The rich-text content of the node, parsed from the `delta`
  /// attribute.
  ///
  /// The parsed [Delta] is cached and invalidated by identity of the raw
  /// attribute value: [updateAttributes] always composes a new attribute
  /// map, so edits refresh the cache naturally.
  ///
  /// Treat the returned instance as immutable — its operations are shared
  /// with the cache and [Delta.add]/[Delta.insert] merge into the last
  /// operation IN PLACE. To derive a new value use `compose`/`slice`, or
  /// deep-copy first: `Delta.fromJson(node.delta!.toJson())`.
  Delta? get delta {
    // read the backing map directly: the public [attributes] getter
    // copies the whole map on every access.
    final raw = _attributes['delta'];
    if (raw is! List) {
      return null;
    }
    if (!identical(raw, _cachedDeltaRaw)) {
      debugDeltaParseCount++;
      _cachedDeltaRaw = raw;
      _cachedDelta = Delta.fromJson(raw);
    }
    return _cachedDelta;
  }

  Map<String, Object> toJson() {
    final map = <String, Object>{
      'type': type,
    };
    if (children.isNotEmpty) {
      map['children'] = children
          .map(
            (node) => node.toJson(),
          )
          .toList(growable: false);
    }
    if (attributes.isNotEmpty) {
      // filter the null value
      map['data'] = attributes..removeWhere((_, value) => value == null);
    }
    return map;
  }

  /// Copy the node
  ///
  /// If the parameters are not provided, the original value will be used.
  ///
  /// Be careful of the children, they will be deep copied if not provided.
  Node copyWith({
    String? type,
    Iterable<Node>? children,
    Attributes? attributes,
  }) {
    final node = Node(
      type: type ?? this.type,
      id: nanoid(6),
      attributes: attributes ?? {...this.attributes},
      children: children ?? [],
    );
    if (children == null && _children.isNotEmpty) {
      for (final child in _children) {
        node._children.add(
          child.copyWith()..parent = node,
        );
      }
    }
    node.externalValues = externalValues;
    node.extraInfos = extraInfos;
    return node;
  }

  /// Deep copy the node
  ///
  /// This is a deep copy of the node, including the children.
  Node deepCopy() {
    return copyWith();
  }

  /// The index of this node inside [parent], amortized O(1).
  ///
  /// The first call after a children mutation re-indexes ALL siblings in
  /// one sweep, so computing the paths of n siblings costs O(n) instead
  /// of the former O(n²) of one `indexOf` per sibling — the editor
  /// resolves paths constantly (selections, rendering, transactions).
  int _indexInParent() {
    final parent = this.parent;
    if (parent == null) {
      return -1;
    }
    if (identical(_indexCacheOwner, parent) &&
        _indexCacheVersion == parent._childrenVersion) {
      return _cachedIndex;
    }
    parent._reindexChildren();
    if (identical(_indexCacheOwner, parent) &&
        _indexCacheVersion == parent._childrenVersion) {
      return _cachedIndex;
    }
    // not present in the parent's children (e.g. mid-unlink): preserve
    // the legacy `indexOf` behavior of returning -1.
    return -1;
  }

  void _reindexChildren() {
    debugReindexCount++;
    final list = children;
    for (var i = 0; i < list.length; i++) {
      final child = list[i];
      child._indexCacheOwner = this;
      child._indexCacheVersion = _childrenVersion;
      child._cachedIndex = i;
    }
  }

  Path _computePath([Path previous = const []]) {
    final parent = this.parent;
    if (parent == null) {
      return previous;
    }
    return parent._computePath([_indexInParent(), ...previous]);
  }

  /// check the integrity of the document (for DEBUG only)
  void checkDocumentIntegrity() {
    // skip the root node
    if (path.isNotEmpty) {
      // if node is rendered in the tree, its parent should not be null
      final errorMessage =
          '''Please submit an issue to https://github.com/Novident/novident-editor/issues if you see this error!
          node = ${toJson()}''';
      assert(
        parent != null,
        errorMessage,
      );
      // also, its parent should contain this node
      assert(
        parent!.children.where((element) => element.id == id).length == 1,
        errorMessage,
      );
    }

    for (final child in children) {
      child.checkDocumentIntegrity();
    }
  }
}

extension NodeEquality on Iterable<Node> {
  bool equals(Iterable<Node> other) {
    if (length != other.length) {
      return false;
    }
    for (var i = 0; i < length; i++) {
      if (!_nodeEquals(elementAt(i), other.elementAt(i))) {
        return false;
      }
    }
    return true;
  }

  bool _nodeEquals<T, U>(T base, U other) =>
      identical(this, other) ||
      base is Node &&
          other is Node &&
          other.type == base.type &&
          other.children.equals(base.children);
}
